name: clock2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  intl: ^0.17.0
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.2.1
  package_info_plus: ^1.4.3+1
  in_app_review: ^2.0.4
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: AlarmClock
      fonts:
        - asset: assets/fonts/alarmClock.ttf
